name: Take screenshots

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  screenshot:
    runs-on: ${{ matrix.os }}
    env:
      DISPLAY: ":1"
    strategy:
      fail-fast: false
      matrix:
        os: ['ubuntu-latest', 'macos-latest', 'windows-latest']
        perl: [ 'latest' ]
        dist: [ 'strawberry' ]
    name: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v1
      with:
        python-version: '3.x'
    - run: pip install meson ninja
    - uses: seanmiddleditch/gha-setup-ninja@master
    - name: Install gtk+-3.0 (Linux)
      if: ${{ startsWith( matrix.os, 'ubuntu-' )  }}
      run: sudo apt-get update && sudo apt-get install -y libgtk-3-dev xvfb
    - name: Install gtk+-3.0 (OSX)
      if: ${{ startsWith( matrix.os, 'macos-' ) }}
      run: brew install gtk+3
    - name: Set up perl
      uses: shogo82148/actions-setup-perl@v1
      with:
        perl-version: latest
        distribution: strawberry
    - run: perl -V
    - run: |    
           cpanm -n Affix https://github.com/sanko/LibUI.pm Imager Imager::Screenshot
           
    - name: Init Xvfb
      if: ${{ startsWith( matrix.os, 'ubuntu-' )  }}
      run: Xvfb :1 &
    - name: Run scripts and take screenshots
      run: |
            perl LibUI.pl            
    - name: Kill Xvfb
      if: ${{ startsWith( matrix.os, 'ubuntu-' )  }}
      run: killall Xvfb
    - name: Upload smoke test artifacts
      uses: actions/upload-artifact@v3.1.1
      with:
        name: screenshot-${{ matrix.os }}-${{ matrix.file }}.png
        path: ${{ github.workspace }}/**/*.png
